### ISSUE TITLE
cannot run INCV individually

### ISSUE THREAD

**Issue by Hugo101** [chenpf1025/noisy_label_understanding_utilizing#4] opened 2020-09-04 19:00 UTC
Hi Pengfei,

As you said, if we only want to use INCV to clean a noisy dataset, we can run INCV.py only. However, it seems we still need to model trained from Verify_Theory.py. Is that correct or we will need to acquire the model in advance indeed?

Thank you!

**Comment by chenpf1025** [comment] 2020-09-24 03:20
Thank you for your interest.

No. In INCV.py, we initialize a model in each iteration, which does not need to acquire any trained model in advance. Please see the 'model.set_weights(weights_initial)' in line 123&164 of INCV.py.

We can clean the noise by running INCV.py only, as shown in the README, e.g.,
    python INCV.py --noise_pattern sym --noise_ratio 0.5 --dataset cifar10

In our code, INCV.py and Verify_Theory.py are independent. Is there any error when you run INCV.py or is there any misunderstanding?

Best,
Pengfei

**Comment by chenpf1025** [comment] 2020-11-21 12:31
I have one more suggestion. The bug is largely caused by the versions of Keras/tf. We use Python 3.6.4, Keras 2.1.6, Tensorflow 1.7.0. In our code, the model should be automatically saved in the "model.fig_generator" using the callback function "ModelCheckpoint". In the callback function, recent versions of keras use "val_accuracy" instead of "val_acc", for which you may not directly get an error but may fail to save the model. Please check the Documentation of Keras if you use a different version.

I will close this issue here. Feel free to reopen it if the bug still exists.

Best,
Pengfei

**Closed** 2020-11-21 12:31 UTC

**Comment by Hugo101** [comment] 2020-11-23 19:17
Thanks Pengfei. I am sorry for the late feedback. I commented the load model part and it works now. I will let you know if I have other questions. Thank you so much!

**Comment by chenpf1025** [comment] 2020-11-24 01:55
Thanks for your valuable feedback. BTW, it could work better sometimes if you save the model (with the highest val acc, using the ModelCheckpoint function) then load it.

**Comment by Hugo101** [comment] 2020-11-24 02:55
Absolutely. Also, your code is quite clear and very easy to follow. I learnt a lot from your code style. Thank you!
